project:
  type: website
  output-dir: docs
  
website:
  title: "Josue Baeza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - href: blog.qmd
        text: Blog
      - href: Baeza_cv.pdf
        text: CV
      # - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/baezaj/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Josue Baeza"

format:
  html:
    theme: cerulean
    toc: true

editor: source