---
title: "Publications"
---

```{r}
#| label: Setup
#| include: false


library(tidyverse)
library(scholar)
library(glue)

```

```{r}
#| label: Fetching publications
#| echo: false


# Retreiving citations from google scholar
pubs <- get_publications("lIYgwaYAAAAJ")

# Getting complete author list
pubs$author <- unlist(lapply(pubs$pubid, function(x){
  get_complete_authors("lIYgwaYAAAAJ", x)
}))

# Getting publication url
pubs$url <- unlist(lapply(pubs$pubid, function(x){
  get_publication_url("lIYgwaYAAAAJ", x)
}))

# Removing my thesis from the list
pubs <- pubs %>% 
  filter(pubid != "Y0pCki6q_DkC")

# Manual edit of kNdYIx-mwKoC
pubid <- "kNdYIx-mwKoC" # bioRxiv preprint from 2018
pubs$journal[pubs$pubid == pubid] <- "bioRxiv"
pubs$url[pubs$pubid == pubid] <- "https://www.biorxiv.org/content/10.1101/472530v3"
pubs$number[pubs$pubid == pubid] <- "472530"

```

```{r}
#| include: true
#| results: asis
#| echo: false


pubs %>%
  arrange(-year) %>% 
  mutate(author = str_replace_all(author, pattern = "J Baeza", replacement = "**J Baeza**"),
         title = str_remove_all(title, "\\*")) %>% 
  glue_data("{author}, ({year}). {title}. *{journal}*, {number}. [{url}]({url}) \n\n") %>%
  print()


```


♦ This article was selected as a Paper of the Week.
